language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_2ed121698a4b_key -iv $encrypted_2ed121698a4b_iv
  -in credentials.json.enc -out credentials.json -d
script:
- python3 app.py
